# Development Docker Compose - Simplified for local development
version: '3.8'

services:
  # Flask Web Application
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=sqlite:///instance/bugtracker.db
    volumes:
      - .:/app
      - ./instance:/app/instance
    networks:
      - bugtracker-dev
    restart: unless-stopped
    command: python app.py

networks:
  bugtracker-dev:
    driver: bridge
